name: Sync Upstream

env:
  UPSTREAM_URL: "https://github.com/anuraghazra/github-readme-stats.git"
  WORKFLOW_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
  UPSTREAM_BRANCH: "master"
  DOWNSTREAM_BRANCH: "main"
  FETCH_ARGS: ""
  MERGE_ARGS: ""
  PUSH_ARGS: ""
  SPAWN_LOGS: "false"

on:
  schedule:
    - cron: '30 3 * * 0'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: GitHub Sync to Upstream Repository
        uses: dabreadman/sync-upstream-repo@v1.3.0
        with: 
          upstream_repo: ${{ env.UPSTREAM_URL }}
          upstream_branch: ${{ env.UPSTREAM_BRANCH }}
          downstream_branch: ${{ env.DOWNSTREAM_BRANCH }}
          token: ${{ env.WORKFLOW_TOKEN }}
          fetch_args: ${{ env.FETCH_ARGS }}
          merge_args: ${{ env.MERGE_ARGS }}
          push_args: ${{ env.PUSH_ARGS }}
          spawn_logs: ${{ env.SPAWN_LOGS }}
